### ISSUE TITLE
[MJAR-41] Cannot specify additional classpath entries in jar manifest when using addClasspath

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-jar-plugin#448]
**[Fredrik Vraalsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fredriv)** opened **[MJAR-41](https://issues.apache.org/jira/browse/MJAR-41?redirect=false)** and commented

The plugin configuration snippet below leads to the generation of an illegal jar manifest file, as it contains two Class-Path entries.  This works in Maven 1.1b2 by adding the following to project.properties:

maven.jar.manifest.classpath.add=true
maven.jar.classpath=help/ resources/

For more information, please see http://www.nabble.com/classpath-in-jar-manifest-t1582724.html

\<plugin>
	\<groupId>org.apache.maven.plugins\</groupId>
	\<artifactId>maven-jar-plugin\</artifactId>
	\<configuration>
		\<archive>
			\<manifest>
				\<addClasspath>true\</addClasspath>
			\</manifest>
			\<manifestEntries>
				\<Class-Path>help/ resources/\</Class-Path>
			\</manifestEntries>
		\</archive>
	\</configuration>
\</plugin>

---

**Affects:** 2.0, 2.1

**Attachments:**
- [MJAR-41.patch](https://issues.apache.org/jira/secure/attachment/12716800/MJAR-41.patch) (_411 bytes_)

**Issue Links:**
- [MJAR-55](https://issues.apache.org/jira/browse/MJAR-55) possibility to add arbitrary elements to the manifest classpath
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Fredrik Vraalsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fredriv)** commented

See http://jira.codehaus.org/browse/MNG-2284 for a simple patch that solved the issue for me.

**Comment by jira-importer** [comment]
**[Fredrik Vraalsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fredriv)** commented

It seems the spec and the implementation are not quite in agreement, unfortunately.

I've tested with multiple Class-Path entries in the manifest file, and this does not seem to work with JDK 1.5.0 update 6 on Windows XP at least.  It gives the following output:

$ java -jar test.jar
12.jun.2006 11:48:10 java.util.jar.Attributes read
WARNING: Duplicate name in Manifest: Class-Path
12.jun.2006 11:48:10 java.util.jar.Attributes read
WARNING: Duplicate name in Manifest: Class-Path

and then I get a NoClassDefFoundError on one of the classes from the first Class-Path entry.

$ java -version
java version "1.5.0_06"
Java(TM) 2 Runtime Environment, Standard Edition (build 1.5.0_06-b05)
Java HotSpot(TM) Client VM (build 1.5.0_06-b05, mixed mode)
